version: "2.2"

services:
  # Selenium hub
  chrome:
    image: selenium/standalone-chrome:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4441:4444
    restart: always

  firefox:
    image: selenium/standalone-firefox:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4442:4444
    restart: always

  opera:
    image: selenium/standalone-opera:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4443:4444
    restart: always

