selenium-hub:
  image: selenium/hub:3.11.0
  ports:
    - 4444:4444
  restart: always #TODO consider to put this in ref. https://gist.github.com/manoj9788/67e248064c89d622cadc6192c66b184d


selenium-node-ch:
  image: selenium/node-chrome:3.4.0-einsteinium
  ports:
    - 5900 #may help in case of some single node restarts or more advance configurations e.g. distributed
  links:
    - selenium-hub:hub
  restart: always #TODO consider to put this in ref. https://gist.github.com/manoj9788/67e248064c89d622cadc6192c66b184d

selenium-node-ff:
  image: selenium/node-firefox:3.4.0-einsteinium
  ports:
    - 5900 #may help in case of some single node restarts or more advance configurations e.g. distributed
  links:
    - selenium-hub:hub
  restart: always #TODO consider to put this in ref. https://gist.github.com/manoj9788/67e248064c89d622cadc6192c66b184d
